---
kind: pipeline
type: docker
name: windows-go116-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: docker-ci
    image: plugins/docker
    settings:
      dry_run: true
      purge: false
      context: 1.16/windows/windowsservercore-1809
      custom_dns: 1.1.1.1
      dockerfile: 1.16/windows/windowsservercore-1809/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.16-windowsservercore-1809
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

  - name: docker-publish
    image: plugins/docker
    settings:
      purge: false
      context: 1.16/windows/windowsservercore-1809
      custom_dns: 1.1.1.1
      dockerfile: 1.16/windows/windowsservercore-1809/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.16-windowsservercore-1809
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
type: docker
name: windows-go116-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-20H2
  - name: docker-ci
    image: rancher/drone-images:docker-20H2
    settings:
      dry_run: true
      purge: false
      context: 1.16/windows/windowsservercore-20H2
      custom_dns: 1.1.1.1
      dockerfile: 1.16/windows/windowsservercore-20H2/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.16-windowsservercore-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

  - name: docker-publish
    image: rancher/drone-images:docker-20H2
    settings:
      purge: false
      context: 1.16/windows/windowsservercore-20H2
      custom_dns: 1.1.1.1
      dockerfile: 1.16/windows/windowsservercore-20H2/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.16-windowsservercore-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
type: docker
name: windows-go116-2022

platform:
  os: windows
  arch: amd64
  version: 2022

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-amd64-ltsc2022
  - name: docker-ci
    image: rancher/drone-images:docker-amd64-ltsc2022
    settings:
      dry_run: true
      purge: false
      context: 1.16/windows/windowsservercore-ltsc2022
      custom_dns: 1.1.1.1
      dockerfile: 1.16/windows/windowsservercore-ltsc2022/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.16-windowsservercore-ltsc2022
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

  - name: docker-publish
    image: rancher/drone-images:docker-amd64-ltsc2022
    settings:
      purge: false
      context: 1.16/windows/windowsservercore-ltsc2022
      custom_dns: 1.1.1.1
      dockerfile: 1.16/windows/windowsservercore-ltsc2022/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.16-windowsservercore-ltsc2022
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
type: docker
name: manifests-go116

platform:
  os: linux
  arch: amd64

steps:
  - name: push-manifest
    image: plugins/manifest
    settings:
      password:
        from_secret: docker_password
      spec: manifest-go116.tmpl
      username:
        from_secret: docker_username
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master

depends_on:
  - windows-go116-1809
  - windows-go116-20H2

---
kind: pipeline
type: docker
name: windows-go115-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: docker-ci
    image: plugins/docker
    settings:
      dry_run: true
      purge: false
      context: 1.15/windows/windowsservercore-1809
      custom_dns: 1.1.1.1
      dockerfile: 1.15/windows/windowsservercore-1809/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.15-windowsservercore-1809
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

  - name: docker-publish
    image: plugins/docker
    settings:
      purge: false
      context: 1.15/windows/windowsservercore-1809
      custom_dns: 1.1.1.1
      dockerfile: 1.15/windows/windowsservercore-1809/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.15-windowsservercore-1809
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
type: docker
name: windows-go115-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-20H2
  - name: docker-ci
    image: rancher/drone-images:docker-20H2
    settings:
      dry_run: true
      purge: false
      context: 1.15/windows/windowsservercore-20H2
      custom_dns: 1.1.1.1
      dockerfile: 1.15/windows/windowsservercore-20H2/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.15-windowsservercore-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

  - name: docker-publish
    image: rancher/drone-images:docker-20H2
    settings:
      purge: false
      context: 1.15/windows/windowsservercore-20H2
      custom_dns: 1.1.1.1
      dockerfile: 1.15/windows/windowsservercore-20H2/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.15-windowsservercore-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
type: docker
name: manifests-go115

platform:
  os: linux
  arch: amd64

steps:
  - name: push-manifest
    image: plugins/manifest
    settings:
      password:
        from_secret: docker_password
      spec: manifest-go115.tmpl
      username:
        from_secret: docker_username
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master

depends_on:
  - windows-go115-1809
  - windows-go115-20H2

---
kind: pipeline
type: docker
name: windows-go114-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: docker-ci
  image: plugins/docker
  settings:
    dry_run: true
    purge: false
    context: 1.14/windows/windowsservercore-1809
    custom_dns: 1.1.1.1
    dockerfile: 1.14/windows/windowsservercore-1809/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/golang
    tag: 1.14-windowsservercore-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - pull_request

- name: docker-publish
  image: plugins/docker
  settings:
    purge: false
    context: 1.14/windows/windowsservercore-1809
    custom_dns: 1.1.1.1
    dockerfile: 1.14/windows/windowsservercore-1809/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/golang
    tag: 1.14-windowsservercore-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/heads/master

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
type: docker
name: windows-go114-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-20H2-amd64
  - name: docker-ci
    image: luthermonson/drone-docker:20H2
    settings:
      dry_run: true
      purge: false
      context: 1.14/windows/windowsservercore-20H2
      custom_dns: 1.1.1.1
      dockerfile: 1.14/windows/windowsservercore-20H2/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.14-windowsservercore-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

  - name: docker-publish
    image: luthermonson/drone-docker:20H2
    settings:
      purge: false
      context: 1.14/windows/windowsservercore-20H2
      custom_dns: 1.1.1.1
      dockerfile: 1.14/windows/windowsservercore-20H2/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.14-windowsservercore-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine


---
kind: pipeline
type: docker
name: manifests-go114

platform:
  os: linux
  arch: amd64

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    password:
      from_secret: docker_password
    spec: manifest-go114.tmpl
    username:
      from_secret: docker_username
  when:
    event:
    - push
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/heads/master

depends_on:
- windows-go114-1809
- windows-go114-20H2

---
kind: pipeline
type: docker
name: windows-go113-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: docker-ci
  image: plugins/docker
  settings:
    dry_run: true
    purge: false
    context: 1.13/windows/windowsservercore-1809
    custom_dns: 1.1.1.1
    dockerfile: 1.13/windows/windowsservercore-1809/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/golang
    tag: 1.13-windowsservercore-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - pull_request

- name: docker-publish
  image: plugins/docker
  settings:
    purge: false
    context: 1.13/windows/windowsservercore-1809
    custom_dns: 1.1.1.1
    dockerfile: 1.13/windows/windowsservercore-1809/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/golang
    tag: 1.13-windowsservercore-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/heads/master

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
type: docker
name: windows-go113-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-20H2-amd64
  - name: docker-ci
    image: luthermonson/drone-docker:20H2
    settings:
      dry_run: true
      purge: false
      context: 1.13/windows/windowsservercore-20H2
      custom_dns: 1.1.1.1
      dockerfile: 1.13/windows/windowsservercore-20H2/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.13-windowsservercore-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

  - name: docker-publish
    image: luthermonson/drone-docker:20H2
    settings:
      purge: false
      context: 1.13/windows/windowsservercore-20H2
      custom_dns: 1.1.1.1
      dockerfile: 1.13/windows/windowsservercore-20H2/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.13-windowsservercore-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
type: docker
name: manifests-go113

platform:
  os: linux
  arch: amd64

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    password:
      from_secret: docker_password
    spec: manifest-go113.tmpl
    username:
      from_secret: docker_username
  when:
    event:
    - push
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/heads/master

depends_on:
- windows-go113-1809
- windows-go113-20H2

---
kind: pipeline
type: docker
name: windows-go112-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: docker-ci
  image: plugins/docker
  settings:
    dry_run: true
    purge: false
    context: 1.12/windows/windowsservercore-1809
    custom_dns: 1.1.1.1
    dockerfile: 1.12/windows/windowsservercore-1809/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/golang
    tag: 1.12-windowsservercore-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - pull_request

- name: docker-publish
  image: plugins/docker
  settings:
    purge: false
    context: 1.12/windows/windowsservercore-1809
    custom_dns: 1.1.1.1
    dockerfile: 1.12/windows/windowsservercore-1809/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/golang
    tag: 1.12-windowsservercore-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/heads/master

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
type: docker
name: windows-go112-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-20H2-amd64
  - name: docker-ci
    image: luthermonson/drone-docker:20H2
    settings:
      dry_run: true
      purge: false
      context: 1.12/windows/windowsservercore-20H2
      custom_dns: 1.1.1.1
      dockerfile: 1.12/windows/windowsservercore-20H2/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.12-windowsservercore-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

  - name: docker-publish
    image: luthermonson/drone-docker:20H2
    settings:
      purge: false
      context: 1.12/windows/windowsservercore-20H2
      custom_dns: 1.1.1.1
      dockerfile: 1.12/windows/windowsservercore-20H2/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/golang
      tag: 1.12-windowsservercore-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
type: docker
name: manifests-go112

platform:
  os: linux
  arch: amd64

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    password:
      from_secret: docker_password
    spec: manifest-go112.tmpl
    username:
      from_secret: docker_username
  when:
    event:
    - push
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/heads/master

depends_on:
- windows-go112-1809
- windows-go112-20H2
