---
kind: pipeline
name: default-windows-1903

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
- name: docker-publish
  image: plugins/docker:windows-1903-amd64
  settings:
    context: 1.12/windows/windowsservercore-1903
    custom_dns: 1.1.1.1
    dockerfile: 1.12/windows/windowsservercore-1903/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/golang
    tag: 1.12-windowsservercore-1903
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/heads/master

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: default-windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: docker-publish
  image: plugins/docker:windows-1809-amd64
  settings:
    context: 1.12/windows/windowsservercore-1809
    custom_dns: 1.1.1.1
    dockerfile: 1.12/windows/windowsservercore-1809/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/golang
    tag: 1.12-windowsservercore-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/heads/master

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: manifests

platform:
  os: linux
  arch: amd64

steps:
- name: push-manifest
  image: plugins/manifest:1.1.0
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: manifest.tmpl
    username:
      from_secret: docker_username
  when:
    event:
    - push
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/heads/master

depends_on:
- default-windows-1809
- default-windows-1903
